#!/usr/bin/env bash
#
# configure-providers.sh
#
# Script to configure any required providers before Terragrunt runs the
# Terraform CLI.
#
##

set -e
set -o pipefail


remove_deprecated_provider_file()
{
    # Remove the deprecated 'provider.tf' file to avoid conflicting with the new file
    # generated by the 'aws_provider' block in the root 'terragrunt.hcl' config
    rm -f provider.tf
}

main()
{
    remove_deprecated_provider_file
}


main "$@"
